//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.config
{

public sealed partial class sign_daily :  Bright.Config.BeanBase 
{
    public sign_daily(JsonElement _json) 
    {
        id = _json.GetProperty("id").GetInt32();
        { var __json0 = _json.GetProperty("reward"); reward = new System.Collections.Generic.List<System.Numerics.Vector3>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { System.Numerics.Vector3 __v0;  { var _json0 = __e0; float __x; __x = _json0.GetProperty("x").GetSingle(); float __y; __y = _json0.GetProperty("y").GetSingle(); float __z; __z = _json0.GetProperty("z").GetSingle();  __v0 = new System.Numerics.Vector3(__x, __y,__z); }  reward.Add(__v0); }   }
        PostInit();
    }

    public sign_daily(int id, System.Collections.Generic.List<System.Numerics.Vector3> reward ) 
    {
        this.id = id;
        this.reward = reward;
        PostInit();
    }

    public static sign_daily Deserializesign_daily(JsonElement _json)
    {
        return new config.sign_daily(_json);
    }

    /// <summary>
    /// 天数
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 奖励
    /// </summary>
    public System.Collections.Generic.List<System.Numerics.Vector3> reward { get; private set; }

    public const int __ID__ = 54950723;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "reward:" + Bright.Common.StringUtil.CollectionToString(reward) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
