//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.config
{

public sealed partial class task :  Bright.Config.BeanBase 
{
    public task(JsonElement _json) 
    {
        id = _json.GetProperty("id").GetInt32();
        group = _json.GetProperty("group").GetInt32();
        { var __json0 = _json.GetProperty("condition"); condition = new System.Collections.Generic.List<System.Numerics.Vector3>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { System.Numerics.Vector3 __v0;  { var _json0 = __e0; float __x; __x = _json0.GetProperty("x").GetSingle(); float __y; __y = _json0.GetProperty("y").GetSingle(); float __z; __z = _json0.GetProperty("z").GetSingle();  __v0 = new System.Numerics.Vector3(__x, __y,__z); }  condition.Add(__v0); }   }
        { var __json0 = _json.GetProperty("reward"); reward = new System.Collections.Generic.List<System.Numerics.Vector3>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { System.Numerics.Vector3 __v0;  { var _json0 = __e0; float __x; __x = _json0.GetProperty("x").GetSingle(); float __y; __y = _json0.GetProperty("y").GetSingle(); float __z; __z = _json0.GetProperty("z").GetSingle();  __v0 = new System.Numerics.Vector3(__x, __y,__z); }  reward.Add(__v0); }   }
        type = _json.GetProperty("type").GetInt32();
        { var __json0 = _json.GetProperty("para"); para = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  para.Add(__v0); }   }
        score = _json.GetProperty("score").GetInt32();
        PostInit();
    }

    public task(int id, int group, System.Collections.Generic.List<System.Numerics.Vector3> condition, System.Collections.Generic.List<System.Numerics.Vector3> reward, int type, System.Collections.Generic.List<int> para, int score ) 
    {
        this.id = id;
        this.group = group;
        this.condition = condition;
        this.reward = reward;
        this.type = type;
        this.para = para;
        this.score = score;
        PostInit();
    }

    public static task Deserializetask(JsonElement _json)
    {
        return new config.task(_json);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 所属组
    /// </summary>
    public int group { get; private set; }
    /// <summary>
    /// 任务接取条件
    /// </summary>
    public System.Collections.Generic.List<System.Numerics.Vector3> condition { get; private set; }
    /// <summary>
    /// 任务奖励
    /// </summary>
    public System.Collections.Generic.List<System.Numerics.Vector3> reward { get; private set; }
    /// <summary>
    /// 任务类型
    /// </summary>
    public int type { get; private set; }
    /// <summary>
    /// 任务参数
    /// </summary>
    public System.Collections.Generic.List<int> para { get; private set; }
    /// <summary>
    /// 点数
    /// </summary>
    public int score { get; private set; }

    public const int __ID__ = -27745103;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "group:" + group + ","
        + "condition:" + Bright.Common.StringUtil.CollectionToString(condition) + ","
        + "reward:" + Bright.Common.StringUtil.CollectionToString(reward) + ","
        + "type:" + type + ","
        + "para:" + Bright.Common.StringUtil.CollectionToString(para) + ","
        + "score:" + score + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
