//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.config
{

public sealed partial class task_type :  Bright.Config.BeanBase 
{
    public task_type(JsonElement _json) 
    {
        id = _json.GetProperty("id").GetInt32();
        onceYn = _json.GetProperty("once_yn").GetInt32();
        PostInit();
    }

    public task_type(int id, int once_yn ) 
    {
        this.id = id;
        this.onceYn = once_yn;
        PostInit();
    }

    public static task_type Deserializetask_type(JsonElement _json)
    {
        return new config.task_type(_json);
    }

    /// <summary>
    /// id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 是否一次性
    /// </summary>
    public int onceYn { get; private set; }

    public const int __ID__ = 1189669384;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "onceYn:" + onceYn + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
