//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg.config
{

public sealed partial class task_score :  Bright.Config.BeanBase 
{
    public task_score(JsonElement _json) 
    {
        id = _json.GetProperty("id").GetInt32();
        tagFunc = _json.GetProperty("tag_func").GetInt32();
        score = _json.GetProperty("score").GetInt32();
        { var __json0 = _json.GetProperty("reward"); reward = new System.Collections.Generic.List<System.Numerics.Vector3>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { System.Numerics.Vector3 __v0;  { var _json0 = __e0; float __x; __x = _json0.GetProperty("x").GetSingle(); float __y; __y = _json0.GetProperty("y").GetSingle(); float __z; __z = _json0.GetProperty("z").GetSingle();  __v0 = new System.Numerics.Vector3(__x, __y,__z); }  reward.Add(__v0); }   }
        PostInit();
    }

    public task_score(int id, int tag_func, int score, System.Collections.Generic.List<System.Numerics.Vector3> reward ) 
    {
        this.id = id;
        this.tagFunc = tag_func;
        this.score = score;
        this.reward = reward;
        PostInit();
    }

    public static task_score Deserializetask_score(JsonElement _json)
    {
        return new config.task_score(_json);
    }

    /// <summary>
    /// 宝箱id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 所属模块id
    /// </summary>
    public int tagFunc { get; private set; }
    /// <summary>
    /// 点数
    /// </summary>
    public int score { get; private set; }
    /// <summary>
    /// 奖励
    /// </summary>
    public System.Collections.Generic.List<System.Numerics.Vector3> reward { get; private set; }

    public const int __ID__ = -1776534140;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "tagFunc:" + tagFunc + ","
        + "score:" + score + ","
        + "reward:" + Bright.Common.StringUtil.CollectionToString(reward) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
