//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.config
{ 

public sealed partial class item :  Bright.Config.BeanBase 
{
    public item(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  id = _json["id"]; }
        { if(!_json["buy_value"].IsNumber) { throw new SerializationException(); }  buyValue = _json["buy_value"]; }
        { if(!_json["sell_value"].IsNumber) { throw new SerializationException(); }  sellValue = _json["sell_value"]; }
        { if(!_json["quality"].IsNumber) { throw new SerializationException(); }  quality = _json["quality"]; }
        { if(!_json["pile_yn"].IsNumber) { throw new SerializationException(); }  pileYn = _json["pile_yn"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  name = _json["name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  desc = _json["desc"]; }
        { var __json0 = _json["desc_value"]; if(!__json0.IsArray) { throw new SerializationException(); } descValue = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  descValue.Add(__v0); }   }
        { if(!_json["icon"].IsString) { throw new SerializationException(); }  icon = _json["icon"]; }
        { if(!_json["img_border"].IsString) { throw new SerializationException(); }  imgBorder = _json["img_border"]; }
        { if(!_json["sort"].IsNumber) { throw new SerializationException(); }  sort = _json["sort"]; }
        { var __json0 = _json["version"]; if(!__json0.IsArray) { throw new SerializationException(); } version = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  version.Add(__v0); }   }
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  type = _json["type"]; }
        PostInit();
    }

    public item(int id, int buy_value, int sell_value, int quality, int pile_yn, string name, string desc, System.Collections.Generic.List<int> desc_value, string icon, string img_border, int sort, System.Collections.Generic.List<int> version, int type ) 
    {
        this.id = id;
        this.buyValue = buy_value;
        this.sellValue = sell_value;
        this.quality = quality;
        this.pileYn = pile_yn;
        this.name = name;
        this.desc = desc;
        this.descValue = desc_value;
        this.icon = icon;
        this.imgBorder = img_border;
        this.sort = sort;
        this.version = version;
        this.type = type;
        
        PostInit();
    }

    public static item Deserializeitem(JSONNode _json)
    {
        return new config.item(_json);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 购买价值
    /// </summary>
    public int buyValue { get; private set; }
    /// <summary>
    /// 出售价值
    /// </summary>
    public int sellValue { get; private set; }
    /// <summary>
    /// 道具品质
    /// </summary>
    public int quality { get; private set; }
    /// <summary>
    /// 可否堆叠
    /// </summary>
    public int pileYn { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 道具描述
    /// </summary>
    public string desc { get; private set; }
    /// <summary>
    /// 物品描述变量
    /// </summary>
    public System.Collections.Generic.List<int> descValue { get; private set; }
    /// <summary>
    /// 图标
    /// </summary>
    public string icon { get; private set; }
    /// <summary>
    /// 图标外框(牌外框)
    /// </summary>
    public string imgBorder { get; private set; }
    /// <summary>
    /// 排序
    /// </summary>
    public int sort { get; private set; }
    /// <summary>
    /// 版本
    /// </summary>
    public System.Collections.Generic.List<int> version { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int type { get; private set; }
    public const int __ID__ = -28054977;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "buyValue:" + buyValue + ","
        + "sellValue:" + sellValue + ","
        + "quality:" + quality + ","
        + "pileYn:" + pileYn + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "descValue:" + Bright.Common.StringUtil.CollectionToString(descValue) + ","
        + "icon:" + icon + ","
        + "imgBorder:" + imgBorder + ","
        + "sort:" + sort + ","
        + "version:" + Bright.Common.StringUtil.CollectionToString(version) + ","
        + "type:" + type + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}